---
title: "Case Study 10"
author: Weishan Bai
date: NOV 11, 2020
output: github_document
always_allow_html: true
---

```{r,include=FALSE}
library(raster)
library(rasterVis)
library(rgdal)
library(ggmap)
library(tidyverse)
library(knitr)
library(ncdf4)
```

```{r,include=FALSE}
# Create afolder to hold the downloaded data
dir.create("data",showWarnings = F) #create a folder to hold the data

lulc_url="https://github.com/adammwilson/DataScienceData/blob/master/inst/extdata/appeears/MCD12Q1.051_aid0001.nc?raw=true"
lst_url="https://github.com/adammwilson/DataScienceData/blob/master/inst/extdata/appeears/MOD11A2.006_aid0001.nc?raw=true"

# download them
download.file(lulc_url,destfile="data/MCD12Q1.051_aid0001.nc", mode="wb")
download.file(lst_url,destfile="data/MOD11A2.006_aid0001.nc", mode="wb")
```
# Load data into R
```{r,include=FALSE}
lulc=stack("data/MCD12Q1.051_aid0001.nc",varname="Land_Cover_Type_1")
lst=stack("data/MOD11A2.006_aid0001.nc",varname="LST_Day_1km")
```
# Explore LULC data
```{r}
lulc=lulc[[13]]
plot(lulc)
```
# Process landcover data
```{r,message=FALSE, warning=FALSE}
  Land_Cover_Type_1 = c(
    Water = 0, 
    `Evergreen Needleleaf forest` = 1, 
    `Evergreen Broadleaf forest` = 2,
    `Deciduous Needleleaf forest` = 3, 
    `Deciduous Broadleaf forest` = 4,
    `Mixed forest` = 5, 
    `Closed shrublands` = 6,
    `Open shrublands` = 7,
    `Woody savannas` = 8, 
    Savannas = 9,
    Grasslands = 10,
    `Permanent wetlands` = 11, 
    Croplands = 12,
    `Urban & built-up` = 13,
    `Cropland/Natural vegetation mosaic` = 14, 
    `Snow & ice` = 15,
    `Barren/Sparsely vegetated` = 16, 
    Unclassified = 254,
    NoDataFill = 255)

lcd=data.frame(
  ID=Land_Cover_Type_1,
  landcover=names(Land_Cover_Type_1),
  col=c("#000080","#008000","#00FF00", "#99CC00","#99FF99", "#339966", "#993366", "#FFCC99", "#CCFFCC", "#FFCC00", "#FF9900", "#006699", "#FFFF00", "#FF0000", "#999966", "#FFFFFF", "#808080", "#000000", "#000000"),
  stringsAsFactors = F)
# colors from https://lpdaac.usgs.gov/about/news_archive/modisterra_land_cover_types_yearly_l3_global_005deg_cmg_mod12c1
kable(head(lcd))

lulc=as.factor(lulc)

# update the RAT with a left join
levels(lulc)=left_join(levels(lulc)[[1]],lcd)
```
# plot it 
```{r,message=FALSE, warning=FALSE,fig.width = 14, fig.height = 9}
p<-gplot(lulc)+
  geom_raster(aes(fill=as.factor(value)))+
  scale_fill_manual(values=levels(lulc)[[1]]$col,
                    labels=levels(lulc)[[1]]$landcover,
                    name="Landcover Type")+
  coord_equal()+
  theme(legend.position = "bottom")+
  guides(fill=guide_legend(ncol=1,byrow=TRUE))
p

```
# Land Surface Temperature
```{r}
plot(lst[[1:12]])
```
# Convert LST to Degrees C
```{r}
offs(lst)=-273.15
plot(lst[[1:10]])
```
# Add Dates to Z (time) dimension
```{r,message=FALSE, warning=FALSE}
names(lst)[1:5]
tdates=names(lst)%>%
  sub(pattern="X",replacement="")%>%
  as.Date("%Y.%m.%d")

names(lst)=1:nlayers(lst)
lst=setZ(lst,tdates)
```
# Part1: Extract timeseries for a point
```{r,message=FALSE, warning=FALSE}
lw=SpatialPoints(data.frame(x= -78.791547,y=43.007211))
projection(lw) ="+proj=longlat"
lw_trans = spTransform(lw,crs(lst))
lw_extract = t(raster::extract(lst,lw_trans,buffer=1000,fun=mean,na.rm=T))
date = getZ(lst)
df1 = cbind.data.frame(date,lw_extract)
p1<- ggplot(df1,aes(date,lw_extract))+geom_point()+geom_smooth(n=811,span=0.05)+ labs(x = "date", y = "Monthly Mean Land Surface Temperature")

p1
```
# Part 2: Summarize weekly data to monthly climatologies
```{r,message=FALSE, warning=FALSE}
tmonth = as.numeric(format(getZ(lst),"%m"))
lst_month =stackApply(lst, indices = tmonth, fun = mean)
names(lst_month)=month.name
p2<-gplot(lst_month) + geom_tile(aes(fill=value)) + 
  scale_fill_gradient2(low = "blue", high = "red", midpoint = 15) +facet_wrap(~variable)+
  theme(axis.text=element_blank())
p2
mean_monthly = cellStats(lst_month,mean)
round(mean_monthly,2)%>%knitr::kable(col.names = "Mean")%>% kable_styling(bootstrap_options = "striped")
```
# Part 3: Summarize Land Surface Temperature by Land Cover
```{r,message=FALSE, warning=FALSE}
lc_resample_lst = resample(lulc, lst, method="ngb")
lcds1=cbind.data.frame(
values(lst_month),
ID=values(lc_resample_lst[[1]]))%>%
na.omit()
tidy_lcds1 = lcds1 %>% gather(key='month',value='value',-ID) %>%
  mutate(ID=as.numeric(ID),month=factor(month,levels=month.name,ordered=T)) 
joined_data = tidy_lcds1%>%left_join(lcd, by = "ID")
filter_data = joined_data%>%filter(landcover%in%c("Urban & built-up","Deciduous Broadleaf forest"))
p3<-ggplot(filter_data,aes(month,value))+geom_jitter(shape=16, position=position_jitter(0.2))+ facet_wrap(~landcover)+ geom_violin(aes(fill=value),colour = "red", fill = "grey")+
  labs(x = "Month", y = "Monthly Mean Land Surface Temperature(C)", title = "Land Surface Temperature in Urban and Forest") +
  theme(axis.text.x = element_text(angle = 90)) +
  theme(plot.title = element_text(hjust = 0.5))
p3
```
